services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    networks:
      - iceberg_env
    container_name: clickhouse-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=246810
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123" # HTTP interface
      - "9002:9002" #Native TCP interface 
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
networks:
  iceberg_env:
    external: true
