version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
      ZOO_CLIENT_PORT: 2181
    volumes:
      - ./zookeeper-data:/data
      - ./zookeeper-datalog:/datalog
    restart: unless-stopped
    networks:
      - clickhouse_net

  clickhouse01:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse01
    hostname: clickhouse01
    ports:
      - "8123:8123"
      - "8003:9000"
    volumes:
      - ./clickhouse01-data:/var/lib/clickhouse
      - ./clickhouse01-logs:/var/log/clickhouse-server
      - ./config/clickhouse01-config.xml:/etc/clickhouse-server/config.d/custom.xml:ro
      - ./config/users.xml:/etc/clickhouse-server/users.d/custom.xml:ro
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - clickhouse_net

  clickhouse02:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse02
    hostname: clickhouse02
    ports:
      - "8124:8123"
      - "8004:9000"
    volumes:
      - ./clickhouse02-data:/var/lib/clickhouse
      - ./clickhouse02-logs:/var/log/clickhouse-server
      - ./config/clickhouse02-config.xml:/etc/clickhouse-server/config.d/custom.xml:ro
      - ./config/users.xml:/etc/clickhouse-server/users.d/custom.xml:ro
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - clickhouse_net

  haproxy:
    image: haproxy:2.8
    container_name: clickhouse-loadbalancer
    ports:
      - "8120:8123"  # Load balanced HTTP interface
      - "8010:9000"  # Load balanced native interface
      - "8404:8404"  # HAProxy stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - clickhouse01
      - clickhouse02
    restart: unless-stopped
    networks:
      - clickhouse_net

networks:
  clickhouse_net:
    driver: bridge
    external: true
