services:
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
  minioserver:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    enviroment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      container_name: minio	
  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
networks:
  default:
    name: iceberg_env
    driver: bridge
